ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-"{{ env }}".chotu.online
CATALOGUE_HOST: catalogue-"{{ env }}".chotu.online
REDIS_HOST: redis-"{{ env }}".chotu.online
USER_HOST: user-"{{ env }}".chotu.online
CART_HOST: cart-"{{ env }}".chotu.online
MYSQL_HOST: mysql-"{{ env }}".chotu.online
SHIPPING_HOST: shipping-"{{ env }}".chotu.online
RABBITMQ_HOST: rabbitmq-"{{ env }}".chotu.online
PAYMENT_HOST: payment-"{{ env }}".chotu.online
