[local]
localhost

[mongodb]
localhost 

[catalogue]
catalogue-dev.chotu.online

[redis]
redis-dev.chotu.online

[user]
user-dev.chotu.online

[cart]
cart-dev.chotu.online

[mysql]
mysql-dev.chotu.online

[shipping]
shipping-dev.chotu.online

[rabbitmq]
rabbitmq-dev.chotu.online

[payment]
payment-dev.chotu.online

[frontend]
frontend-dev.chotu.online
